# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 07:01
from __future__ import unicode_literals

import allauth.socialaccount.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='extra_data',
            field=allauth.socialaccount.fields.JSONField(default=dict, verbose_name='extra data'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('openid', 'OpenID')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='uid',
            field=models.CharField(max_length=191, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='client_id',
            field=models.CharField(help_text='App ID, or consumer key', max_length=191, verbose_name='client id'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='key',
            field=models.CharField(blank=True, help_text='Key', max_length=191, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[('openid', 'OpenID')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='secret',
            field=models.CharField(help_text='API secret, client secret, or consumer secret', max_length=191, verbose_name='secret key'),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='token',
            field=models.TextField(help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token'),
        ),
    ]
