# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160520_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='indicators',
            field=models.ManyToManyField(to='website.Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
