# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160523_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='logo',
            field=models.ImageField(blank=True, upload_to='topics/%Y/%m/%d/'),
        ),
    ]
