professions = [
    'advokatas',
    'agronomas',
    'aktorius',
    'archeologas',
    'architektas',
    'atstovas spaudai',
    'auditorius',
    'bendrosios praktikos slaugytojas',
    'bibliotekininkas',
    'biologas',
    'buhalteris',
    'chemikas',
    'dailininkas',
    'dietologas',
    'drabužių dizaineris',
    'dėstytojas',
    'ekonomistas',
    'filosofas',
    'finansininkas',
    'fizikas',
    'geologas',
    'gydytojas',
    'inžinierius',
    'istorikas',
    'kartografas',
    'konstruktorius',
    'matematikas',
    'meteorologas',
    'mokytojas',
    'muzikantas',
    'prodiuseris',
    'programuotojas',
    'prokuroras',
    'psichologas',
    'rašytojas',
    'socialinis darbuotojas',
    'statistikas',
    'teisininkas',
    'vaistininkas',
    'vertėjas',
    'viešojo administravimo specialistas',
    'zoologas',
    'žinių pranešėjas',
    'žurnalistas',
]


first_names = {
    'mantas',
}
