# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'vrk/kadencijos.csv')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='source_id',
            field=models.CharField(default='-', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='curator',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='actors/%Y/%m/%d/', verbose_name='Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Domėjimosi sritis'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([('source', 'source_id')]),
        ),
    ]
