# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Pavardė'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='actors/%Y/%m/%d/', verbose_name='Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='title',
            field=models.CharField(help_text='Autoriaus profesija arba domėjimosi sritis atitinkanti citatos tekstą.', max_length=255, verbose_name='Autoriaus sritis'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='counterargument',
            field=models.BooleanField(default=False, verbose_name='Kontrargumentas'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='actors/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='reference_link',
            field=models.URLField(blank=True, help_text='Nuoroda į šaltinį, apie kurį autorius kalba savo citatoje.', verbose_name='Cituojamo šaltinio nuoroda'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(help_text='Citatos tekste turėtų būti išreikšta viena mintis. Stenkitės citatos tekstą išlaikyti kiek galima trumpesnį.', verbose_name='Citatos tekstas'),
        ),
        migrations.AlterField(
            model_name='source',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Actor', verbose_name='Citatos autorius'),
        ),
        migrations.AlterField(
            model_name='source',
            name='actor_title',
            field=models.CharField(blank=True, help_text='Autoriaus profesija arba domėjimosi sritis atitinkanti citatos tekstą.', max_length=64, verbose_name='Autoriaus sritis'),
        ),
        migrations.AlterField(
            model_name='source',
            name='position',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_link',
            field=models.URLField(max_length=255, verbose_name='Šaltinio nuoroda'),
        ),
        migrations.AlterField(
            model_name='source',
            name='timestamp',
            field=models.DateTimeField(help_text='Datos formatas: yyyy-mm-dd HH:MM:SS', verbose_name='Kada paskelbtas šaltinis?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='topics/%Y/%m/%d/'),
        ),
    ]
