# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0002_auto_20160712_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source_link',
            field=models.URLField(blank=True, max_length=255, unique=True, verbose_name='Šaltinio nuoroda'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Kada buvo priimtas sprendimas?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='source',
            name='actor_title',
            field=models.CharField(blank=True, help_text='Autoriaus profesija arba domėjimosi sritis atitinkanti citatos tekstą.', max_length=64, verbose_name='Autoriaus veiklos sritis'),
        ),
        migrations.AlterField(
            model_name='source',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Kada paskelbtas šaltinis?'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('topic', 'content_type', 'object_id')]),
        ),
    ]
