# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0002_auto_20160725_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
