# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manopozicija', '0004_auto_20160713_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatorapproval',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='topiccurator',
            name='curator',
        ),
        migrations.AddField(
            model_name='curatorapproval',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topiccurator',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
