# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0007_auto_20160714_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curator_downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='curator_upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 15, 4, 4, 10, 388253)),
            preserve_default=False,
        ),
    ]
