# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0008_auto_20160715_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Post'),
            preserve_default=False,
        ),
    ]
