# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manopozicija', '0009_argument_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorArgumentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='ActorPostPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Actor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Post')),
            ],
        ),
        migrations.CreateModel(
            name='UserArgumentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserPosition',
            new_name='UserPostPosition',
        ),
        migrations.RenameModel(
            old_name='Argument',
            new_name='PostArgument',
        ),
        migrations.AlterUniqueTogether(
            name='userpostposition',
            unique_together=set([('user', 'post')]),
        ),
        migrations.AddField(
            model_name='userargumentposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='actorpostposition',
            unique_together=set([('actor', 'post')]),
        ),
    ]
