# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0010_auto_20160721_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='actorargumentposition',
            name='argument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Argument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userargumentposition',
            name='argument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manopozicija.Argument'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='actorargumentposition',
            unique_together=set([('actor', 'argument')]),
        ),
        migrations.AlterUniqueTogether(
            name='userargumentposition',
            unique_together=set([('user', 'argument')]),
        ),
        migrations.AlterUniqueTogether(
            name='argument',
            unique_together=set([('topic', 'title')]),
        ),
    ]
