# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 09:23
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manopozicija', '0011_auto_20160721_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('members', models.ManyToManyField(related_name='_group_members_+', related_query_name='ingroup', to='manopozicija.Actor')),
            ],
        ),
    ]
